# Generated by Django 4.2.9 on 2024-03-06 11:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='prompt',
            field=models.ManyToManyField(blank=True, help_text="<br><strong style='color: #34495e; font-size: 1.3em;'>Please share any general reflections you have about the text you are reading. You can use the prompts above to focus your thinking.</strong><br>", related_name='journal_entries', to='education.journalentryprompt'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Optional if providing content in another format below, e.g. audio/video.', null=True),
        ),
    ]
